#!/usr/bin/env python3
"""Turn a MAME debugger trace into an expected FETCH list for the testbench.

    python scripts/parse_mame_trace.py <trace.tr> <out.txt> [--past-loops]

MAME's trace has one line per instruction; the testbench records every fetch,
extension words included. PCs a small positive distance apart are expanded to
cur, cur+2 .. next-2; after a branch the length is unknown, so only the PC is
emitted. The testbench matches the list as an in-order subsequence of its own
fetch trace.

  "(loops for N instructions)"  parsing stops here unless --past-loops: a
      collapsed loop (gogomile's boot delay is 131,068 instructions) is too
      long for a routine regression.
  "(interrupted at ..., IRQ n)"  always stops: MAME is now in an ISR and the
      testbench's boot case runs with no interrupts.
"""
import re, sys

def main():
    args = [a for a in sys.argv[1:] if not a.startswith('--')]
    past = '--past-loops' in sys.argv
    if len(args) != 2:
        sys.exit(__doc__)
    src, dst = args

    pcs, stop = [], None
    for line in open(src, encoding='utf-8', errors='replace'):
        s = line.strip()
        if s.startswith('(interrupted'):
            stop = s
            break
        if s.startswith('(loops'):
            if not past:
                stop = s
                break
            continue
        m = re.match(r'^([0-9A-Fa-f]{6,8}):\s', s)
        if m:
            pcs.append(int(m.group(1), 16))

    words, expanded, branches = [], 0, 0
    for i, pc in enumerate(pcs):
        nxt = pcs[i+1] if i + 1 < len(pcs) else None
        if nxt is not None and 0 < (nxt - pc) <= 12:
            for a in range(pc, nxt, 2):
                words.append(a)
            expanded += 1
        else:
            words.append(pc)
            branches += 1

    with open(dst, 'w') as f:
        f.write("// Expected instruction-fetch addresses, from a MAME debugger trace.\n")
        f.write("// Generated by scripts/parse_mame_trace.py -- do not hand-edit.\n")
        f.write(f"// source: {src}\n")
        f.write("// Match as an in-order SUBSEQUENCE of the RTL fetch trace.\n")
        for a in words:
            f.write(f"{a:08x}\n")

    print(f"{len(pcs)} instructions -> {len(words)} fetch words -> {dst}")
    print(f"  {expanded} expanded from PC deltas, {branches} branch/jump PCs left unexpanded")
    print(f"  range {pcs[0]:06X}..{pcs[-1]:06X}")
    if stop:
        print(f"  stopped at: {stop}")
main()
